### ISSUE TITLE
Errore nel progetto consegnato

### ISSUE THREAD

**Issue by fulcorno** [TdP-prove-finali/DeLeoEmanuele#1]
Sto valutando il tuo progetto, ma ottengo:
java.sql.SQLSyntaxErrorException: (conn=21) Unknown column 'dataPartenza' in 'field list'
	at it.polito.tdp.SimulatoreTrasportoMerce.DAO.DAO.addOrdine(DAO.java:64)

**Comment by manny9797** [comment]
Dev'essere un errore dovuto agli ultimi commit in remoto che ho fatto (non
potevo più fare push sul branch master mi dava un errore. Provo a risolvere
subito

Il mer 6 lug 2022, 13:07 Fulvio Corno ***@***.***> ha scritto:

**Comment by manny9797** [comment]
Ok ho capito perché, le chiedo scusa... Il file SQL non è aggiornato. Lo
cambio subito

Il mer 6 lug 2022, 13:06 Fulvio Corno ***@***.***> ha scritto:

**Comment by manny9797** [comment]
Fatto le chiedo scusa, ho modificato il file SQL dopo averlo messo su
GitHub e ovviamente non mi ha aggiornato il file, ora dovrebbe essere a
posto

Il mer 6 lug 2022, 13:06 Fulvio Corno ***@***.***> ha scritto:

**Comment by fulcorno** [comment]
ok, tutto a posto

**Comment by manny9797** [comment]
Se mi è ancora concesso, vorrei eseguire un'impaginazione fatta bene del file word della relazione  entro stasera . Nel mentre la ringrazio per tutto.
